name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: |
          docker build -t ghcr.io/roshaan1103/k8sagro-helm-app:${{ github.sha }} app/

      - name: Push Image
        run: |
          docker push ghcr.io/roshaan1103/k8sagro-helm-app:${{ github.sha }}
